nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://192.168.151.20']
        allow_methods: ['GET', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/search-suggestions': null
